### ISSUE TITLE
Webpack + require behaves differently when using run_config.json or not

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#131]
We have a weird rule in `webpack.common.js`, probably with the goal of loading "built-in" Korp HTML-templates as files and custom ones as the content of the file:

```
            {
                test: /\.html$/,
                exclude: [path.resolve(korpConfigDir, "./views/")],
                use: [
                    { loader: "file-loader" },
                    {
                        loader: "extract-loader",
                        options: { publicPath: "" },
                    },
                    { loader: "html-loader" },
                ],
            },
            {
                test: /\.html$/,
                include: [path.resolve(korpConfigDir, "./views/")],
                use: [
                    {
                        loader: "html-loader",
                        options: {
                            minimize: true,
                            conservativeCollapse: false,
                        },
                    },
                ],
            },
```

This actually makes Korp behave in different ways when using a `run_config.json` or not. If using `run_config.json` (as we do), `require("../views/extendedlist.html")` will resolve to a file path, but if removing the file and using the configuration in the same repo as the code, it will resolve to the content of the file.

**Comment by simongray** [comment]
I wonder if there any interest in fixing this bug? It has been more than 9 months now since I made [a tiny PR for it](https://github.com/spraakbanken/korp-frontend/pull/130). I know that the priorities of språkbanken and random Clarin developers like myself don't necessarily line up, but since this is a simple logical bug in your code, maybe it should just get fixed?

I am no JavaScript wizard, but in my mind, `require("../views/extendedlist.html")` basically stands in for _"include the contents of ../views/extendedlist.html"_ in pretty much all of the programming languages I know, rather than _"turn this relative URL into an absolute one"_, which seems to be the other usage @majsan is referring to.

Again, not a Javascript wizard at all, bit it seems like you could just reduce this down to the one rule saying _"include the contents of ../views/extendedlist.html"_ and then any usages in your codebase where you treat it as a URL need to be changed to treat it as the contents of the file. I think maybe the only usage is the one line I changed in my PR?

**Comment by majsan** [comment]
There is absolutely interest in fixing this! However, I made the judgement that this was somewhat time consuming to fix, while we had other more severe and/or easy to fix bugs. Maybe I am wrong, I will give it some time soon, hopefully this week.

**Comment by majsan** [comment]
Fixed!

**Comment by simongray** [comment]
Thanks for taking the time to fix this! I see that your fix was a bit more work than I had hypothesized. :)

**Comment by majsan** [comment]
No problem. A bit more work, but it was only improvements!
