### ISSUE TITLE
Make all requests with corpus-key with POST method

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#214]
Make all requests with corpus-key with POST method, moving the query parameters to the message body. This is because there is a max URL-length.

**Comment by janiemi** [comment]
I’ve been implementing this, because of Apache’s URL length limit. The JSON buttons use GET, however, as I haven’t yet had time to try to find out how to make them use POST and as I thought that some users might wish to have the complete backend URL (but they won’t work if a large number of corpora are selected).

If you haven’t yet implemented this yourselves and if you are interested in my partial solution, I can make a pull request.

**Comment by majsan** [comment]
@janiemi Yes, please send a pull request!

And regarding the JSON-button. Maybe it would be possible to create a form with a submit button which will return the JSON, but I'm not sure. Something to try.

**Comment by janiemi** [comment]
I now submitted #215. The JSON buttons will need to be handled separately. I think the form-based solution you suggested could be worth trying, but I most likely won’t have time to do that, at least not in the near future.

**Comment by phildiderichsen** [comment]
I have a concern about moving the corpus-keys to POST: With everything encoded in GET parameters, it is easy to share any corpus query (including, very importantly, any "custom corpus" defined by various corpus-keys and/or search attribute values) by simply sharing the full URL as a link. This very convenient functionality disappears with POST.

I fully appreciate the Apache URL length limit as I've struggled with it myself. But might there be a way to preserve the GET functionality, at least in the (probably most?) cases where the number of corpora selected will not break the URL length limit?

**Comment by majsan** [comment]
I agree, and it even slows down the development some, since one cannot just double-click the requests in the dev tools anymore. 

I will open a new issue with this suggestion.

**Comment by majsan** [comment]
Superseded by #216
