### ISSUE TITLE
Order of structural attributes in the sidebar

### ISSUE THREAD

**Issue by starkadur** [spraakbanken/korp-frontend#296]
In the documentation for the frontend it says: 
"order: Order of attribute in the sidebar. Attributes with a lower order-value will be placed above attributes with a higher order-value."

I does not seem to have any effect to include "order" in there yaml-file for structural settings. The order of the structural attributes, as they appear in the yaml-file for each corpus, seems to decide the order. 

So if I have a custom attribute, is it possible to have that appear at the top, or even in the second place, in the sidebar, or will it always appear after the attributes listed under struct_attribtues in the yaml-file for the corpus?

**Comment by majsan** [comment]
This is wrong in the documentation because we stopped using order. And it is as described, that custom attributes are always put at the end of either the word attributes or the structural attributes depending on type. It would be nice to have the option to mix them into the other arrays, but not a priority now unfortunately.

I will remove the faulty information from the frontend documentation and we will add the correct information somewhere.
