### ISSUE TITLE
KWIC downloading broken

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#53]
KWIC downloading is partially broken.

- [x] Downloading KWIC from the context view results in an empty file.
- [x] Downloading KWIC when "in order" is disabled also results in an empty file, or, when selecting "one token per row", a crash .
- [x] TSV uses spaces instead of tabs.

**Comment by majsan** [comment]
All of this have been fixed, although downloading "one sentence per row" and disabling "in order" have never worked well, due to the fact that we have one column for match, but the searches can contain many matches. Current solution: all the tokens are put in the left context and "match_position" contains the matches, comma-separated.
